lib/leyden_jar_web/router.ex
defmodule LeydenJarWeb.Router do
  use LeydenJarWeb, :router

  import LeydenJarWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LeydenJarWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LeydenJarWeb do
    pipe_through :browser
    get "/input/post", PostController, :post
    live "/", PageLive, :index
  end

  # Other scopes may use custom stacks.
  # scope "/api", LeydenJarWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: LeydenJarWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", LeydenJarWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", LeydenJarWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/jars", JarLive.Index, :index
    live "/jars/new", JarLive.Index, :new
    live "/jars/:id/edit", JarLive.Index, :edit

    live "/jars/:id", JarLive.Show, :show
    live "/jars/:id/show/edit", JarLive.Show, :edit

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", LeydenJarWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/leyden_jar_web/live/jar_live/form_component.ex
defmodule LeydenJarWeb.JarLive.FormComponent do
  use LeydenJarWeb, :live_component

  alias LeydenJar.Jars

  @impl true
  def update(%{jar: jar} = assigns, socket) do
    changeset = Jars.change_jar(jar)

    {:ok,
     socket
     |> assign(assigns)
     |> assign(:changeset, changeset)}
  end

  @impl true
  def handle_event(
        "validate",
        %{"jar" => jar_params},
        %{assigns: %{user_id: user_id}} = socket
      ) do
    changeset =
      socket.assigns.jar
      |> Jars.change_jar(jar_params)
      |> Map.put(:action, :validate)
      |> Map.put(:user_id, user_id)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event(
        "validate",
        %{"jar" => jar_params},
        socket
      ) do
    changeset =
      socket.assigns.jar
      |> Jars.change_jar(jar_params)
      |> Map.put(:action, :validate)

    {:noreply, assign(socket, :changeset, changeset)}
  end

  def handle_event("save", %{"jar" => jar_params}, %{assigns: %{user_id: user_id}} = socket) do
    save_jar(
      socket,
      socket.assigns.action,
      jar_params |> Map.put("user_id", user_id)
    )
  end

  defp save_jar(socket, :edit, jar_params) do
    case Jars.update_jar(socket.assigns.jar, jar_params) do
      {:ok, _jar} ->
        {:noreply,
         socket
         |> put_flash(:info, "Jar updated successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, :changeset, changeset)}
    end
  end

  defp save_jar(socket, :new, jar_params) do
    case Jars.create_jar(jar_params) do
      {:ok, _jar} ->
        {:noreply,
         socket
         |> put_flash(:info, "Jar created successfully")
         |> push_redirect(to: socket.assigns.return_to)}

      {:error, %Ecto.Changeset{} = changeset} ->
        {:noreply, assign(socket, changeset: changeset)}
    end
  end
end

lib/leyden_jar_web/live/jar_live/index.ex
defmodule LeydenJarWeb.JarLive.Index do
  use LeydenJarWeb, :live_view

  alias LeydenJar.Jars
  alias LeydenJar.Jars.Jar
  alias LeydenJar.Accounts

  @impl true
  def mount(_params, session, socket) do
    if connected?(socket),
      do: Phoenix.PubSub.subscribe(LeydenJar.PubSub, "jars")

    current_user =
      session["user_token"] && Accounts.get_user_by_session_token(session["user_token"])

    {:ok,
     socket
     |> assign(:jars, Jars.list_jars_by_user_id(current_user.id))
     |> assign(:user_id, current_user.id)}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {:noreply, apply_action(socket, socket.assigns.live_action, params)}
  end

  defp apply_action(socket, :edit, %{"id" => id}) do
    socket
    |> assign(:page_title, "Edit Jar")
    |> assign(:jar, Jars.get_jar!(id))
  end

  defp apply_action(socket, :new, _params) do
    socket
    |> assign(:page_title, "New Jar")
    |> assign(:jar, %Jar{})
  end

  defp apply_action(socket, :index, _params) do
    socket
    |> assign(:page_title, "Listing Jars")
    |> assign(:jar, nil)
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    jar = Jars.get_jar!(id)
    {:ok, _} = Jars.delete_jar(jar)

    {:noreply, assign(socket, :jars, Jars.list_jars())}
  end

  @impl true
  def handle_info({:jar_updated, %{id: id} = jar}, %{assigns: %{jars: jars}} = socket) do
    jars =
      Enum.map(jars, fn
        %{id: ^id} -> jar
        p -> p
      end)

    {:noreply, assign(socket, jars: jars)}
  end

  # @impl true
  # def handle_info({:jar_updated, jar}, socket) do
  #   {:noreply, assign(socket, jar: jar)}
  # end

  # defp list_jars(user_id) do
  #   Jars.list_jars_by_user_id(user_id)
  # end
end

lib/leyden_jar_web/live/jar_live/show.ex
defmodule LeydenJarWeb.JarLive.Show do
  use LeydenJarWeb, :live_view

  import Ecto.Query, warn: false

  alias LeydenJar.Jars
  alias LeydenJar.Accounts

  @impl true
  def mount(%{"id" => id}, session, socket) do
    if connected?(socket),
      do: Phoenix.PubSub.subscribe(LeydenJar.PubSub, "jar:" <> id)

    current_user =
      session["user_token"] && Accounts.get_user_by_session_token(session["user_token"])

    {:ok,
     socket
     |> assign(:current_user, current_user)}
  end

  @impl true
  def handle_params(%{"id" => id, "session" => param_session_id}, _, socket) do
    jar = Jars.get_jar!(id, preload: [:jar_sessions])

    session =
      jar.jar_sessions
      |> Enum.find(fn %{id: session_id} -> String.to_integer(param_session_id) == session_id end)
      |> LeydenJar.Repo.preload(:posts)

    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:jar, jar)
     |> assign(:session, session)}
  end

  @spec handle_params(map, any, Phoenix.LiveView.Socket.t()) ::
          {:noreply, Phoenix.LiveView.Socket.t()}
  def handle_params(%{"id" => id}, _, socket) do
    jar = Jars.get_jar!(id, preload: [:jar_sessions])
    session = Jars.get_latest_session_from_jar_id!(id)

    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:jar, jar)
     |> assign(:session, session)}
  end

  @impl true
  def handle_event(
        "load-chart",
        _,
        %{assigns: %{session: %LeydenJar.Jars.Session{id: id}} = assigns} = socket
      ) do
    # sql = """
    # select * from jar_posts jp where (jp.body ->> 'wh')::int in
    # (SELECT distinct (jp2.body #>>'{wh}')::int AS wh from jar_posts jp2 order by wh desc limit 1)
    # order by jp.id desc;
    # """

    # %Postgrex.Result{rows: rows, columns: columns} =
    #   Ecto.Adapters.SQL.query!(
    #     LeydenJar.Repo,
    #     sql
    #   )

    # {_, body_index} =
    #   columns
    #   |> Enum.with_index()
    #   |> Enum.find(fn {value, _index} -> value == "body" end)
    #   |> IO.inspect()

    # for row <- rows do
    #   Enum.at(row, body_index) |> IO.inspect()
    # end

    # data =
    #   Enum.map(rows, fn row -> Enum.at(row, body_index) end)
    #   |> Enum.map(fn %{"amp" => amp, "temp" => temp} ->
    #     %{amp: scaleString(amp, 1000, 2), temp: scaleString(temp, 10, 1)}
    #   end)

    # posts =
    #   from(p in LeydenJar.Jars.Post, where: p.jar_id == ^id, order_by: :inserted_at, limit: 1000)
    #   |> LeydenJar.Repo.all()

    IO.inspect(assigns |> Map.keys())
    posts_q = from p in LeydenJar.Jars.Post, order_by: [asc: :inserted_at]

    %{posts: posts} =
      from(s in LeydenJar.Jars.Session,
        where: s.id == ^id,
        order_by: [desc: :wh],
        limit: 1,
        preload: [posts: ^posts_q]
      )
      |> LeydenJar.Repo.one()

    data =
      posts
      |> Enum.map(fn %{body: %{"amp" => amp, "temp" => temp}} ->
        %{amp: scaleString(amp, 1000, 2), temp: scaleString(temp, 10, 1)}
      end)

    {:noreply,
     socket
     |> push_event("inital_data", %{new_data: data})}
  end

  @impl true
  def handle_info({:jar_updated, %{id: id}}, socket) do
    {:noreply, assign(socket, jar: Jars.get_jar!(id, preload: [:jar_sessions]))}
  end

  def handle_info(
        {:new_post, %LeydenJar.Jars.Post{body: %{"amp" => amp, "temp" => temp}}},
        socket
      ) do
    {
      :noreply,
      push_event(socket, "push_data", %{
        new_data: %{
          amp: scaleString(amp, 1000, 2),
          temp: scaleString(temp, 10, 1)
        }
      })
    }
  end

  def handle_info({:change_session, id}, socket) do
    {:noreply, push_patch(socket, to: "jars/1?session=305")}
  end

  defp page_title(:show), do: "Show Jar"
  defp page_title(:edit), do: "Edit Jar"
end

lib/leyden_jar_web/live/live_helpers.ex
defmodule LeydenJarWeb.LiveHelpers do
  import Phoenix.LiveView.Helpers

  @doc """
  Renders a component inside the `LeydenJarWeb.ModalComponent` component.

  The rendered modal receives a `:return_to` option to properly update
  the URL when the modal is closed.

  ## Examples

      <%= live_modal @socket, LeydenJarWeb.PostLive.FormComponent,
        id: @post.id || :new,
        action: @live_action,
        post: @post,
        return_to: Routes.post_index_path(@socket, :index) %>
  """
  def live_modal(socket, component, opts) do
    path = Keyword.fetch!(opts, :return_to)
    modal_opts = [id: :modal, return_to: path, component: component, opts: opts]
    live_component(socket, LeydenJarWeb.ModalComponent, modal_opts)
  end

  def last_post(nil), do: %{}

  def last_post(post) do
    case Jason.decode(post) do
      {:ok, result} -> result
      _ -> %{}
    end
  end

  def last_post(_), do: %{}
  def last_post(), do: %{}

  @spec jar_state(n :: any) :: String.t()
  def jar_state(n) do
    case n do
      0 -> "Starting"
      1 -> "Not Connected"
      2 -> "EV Connected"
      3 -> "Charging"
      4 -> "Vent Required"
      5 -> "Diode Check Failed"
      6 -> "GFCI Fault"
      7 -> "No Earth Ground"
      8 -> "Stuck Relay"
      9 -> "GFCI Self Test Failed"
      10 -> "Over Temperature"
      11 -> "Over Current"
      254 -> "Waiting"
      255 -> "Disabled"
      _ -> "Invalid"
    end
  end

  def updated_since(datetime) do
    {:ok, time} = Timex.format(datetime, "{relative}", :relative)
    time
  end

  def jar_state_color(n) do
    case n do
      # Starting
      0 -> " bg-purple-100"
      # Not Connected
      1 -> " bg-gray-200"
      # EV Connected
      2 -> " bg-yellow-100"
      # Charging
      3 -> " bg-green-100"
      # Vent Required
      4 -> " bg-red-100"
      # Diode Check Failed
      5 -> " bg-red-100"
      # GFCI Fault
      6 -> " bg-red-100"
      # No Earth Ground
      7 -> " bg-red-100"
      # Stuck Relay
      8 -> " bg-red-100"
      # GFCI Self Test Failed
      9 -> " bg-red-100"
      # Over Temperature
      10 -> " bg-red-100"
      # Over Current
      11 -> " bg-red-100"
      # Waiting
      254 -> " bg-blue-100"
      # Disabled
      255 -> " bg-gray-400"
      _ -> ""
    end
  end

  def scaleString(string, scale, precision) do
    tmpval = string / scale
    :erlang.float_to_binary(tmpval, decimals: precision)
  end
end

lib/leyden_jar_web/live/modal_component.ex
defmodule LeydenJarWeb.ModalComponent do
  use LeydenJarWeb, :live_component

  @impl true
  def render(assigns) do
    ~L"""
    <div
      id="<%= @id %>"
      phx-capture-click="close"
      phx-window-keydown="close"
      phx-key="escape"
      phx-target="#<%= @id %>"
      phx-page-loading
      class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
      <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
        <!--
          Background overlay, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0"
            To: "opacity-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100"
            To: "opacity-0"
        -->
        <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true"></div>

        <!-- This element is to trick the browser into centering the modal contents. -->
        <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>

        <!--
          Modal panel, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            To: "opacity-100 translate-y-0 sm:scale-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100 translate-y-0 sm:scale-100"
            To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        -->
          <%= live_component @socket, @component, @opts %>
      </div>
    </div>
    """
  end

  @impl true
  def handle_event("close", _, socket) do
    {:noreply, push_patch(socket, to: socket.assigns.return_to)}
  end
end

lib/leyden_jar_web/live/page_live.ex
defmodule LeydenJarWeb.PageLive do
  use LeydenJarWeb, :live_view
  alias LeydenJar.Accounts

  @impl true
  def mount(_params, session, socket) do
    if user = session["user_token"] && Accounts.get_user_by_session_token(session["user_token"]) do
      {:ok, assign(socket, current_user: user)}
    else
      {:ok, assign(socket, current_user: nil)}
    end
  end

  # @impl true
  # def handle_event("suggest", %{"q" => query}, socket) do
  #   {:noreply, assign(socket, results: search(query), query: query)}
  # end

  # @impl true
  # def handle_event("search", %{"q" => query}, socket) do
  #   case search(query) do
  #     %{^query => vsn} ->
  #       {:noreply, redirect(socket, external: "https://hexdocs.pm/#{query}/#{vsn}")}

  #     _ ->
  #       {:noreply,
  #        socket
  #        |> put_flash(:error, "No dependencies found matching \"#{query}\"")
  #        |> assign(results: %{}, query: query)}
  #   end
  # end

  # defp search(query) do
  #   if not LeydenJarWeb.Endpoint.config(:code_reloader) do
  #     raise "action disabled when not in development"
  #   end

  #   for {app, desc, vsn} <- Application.started_applications(),
  #       app = to_string(app),
  #       String.starts_with?(app, query) and not List.starts_with?(desc, ~c"ERTS"),
  #       into: %{},
  #       do: {app, vsn}
  # end
end

lib/leyden_jar_web/live/jar_live/form_component.html.leex
<div class="inline-block align-bottom bg-white rounded-lg px-4 pt-5 pb-4 text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full sm:p-6">
  <%= f = form_for @changeset, "#",
    id: "jar-form",
    phx_target: @myself,
    phx_change: "validate",
    phx_submit: "save" %>

  <div class="hidden sm:block absolute top-0 right-0 pt-4 pr-4">
    <%= live_patch to: @return_to, class: "bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" do %>
      <span class="sr-only">Close</span>
      <!-- Heroicon name: outline/x -->
      <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
      </svg>
    <% end %>
  </div>

  <div class="sm:flex sm:items-start">
    <div class="mx-auto flex-shrink-0 flex items-center justify-center h-12 w-12 sm:mx-0 sm:h-10 sm:w-10">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-20 w-20 text-black" viewBox="0 0 20 20" fill="currentColor">
        <path fill-rule="evenodd" d="M7 2a1 1 0 00-.707 1.707L7 4.414v3.758a1 1 0 01-.293.707l-4 4C.817 14.769 2.156 18 4.828 18h10.343c2.673 0 4.012-3.231 2.122-5.121l-4-4A1 1 0 0113 8.172V4.414l.707-.707A1 1 0 0013 2H7zm2 6.172V4h2v4.172a3 3 0 00.879 2.12l1.027 1.028a4 4 0 00-2.171.102l-.47.156a4 4 0 01-2.53 0l-.563-.187a1.993 1.993 0 00-.114-.035l1.063-1.063A3 3 0 009 8.172z" clip-rule="evenodd" />
      </svg>
         
    </div>

    <div class="w-full mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
      <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
        <%= @title %>
      </h3>
      <div class="mt-2">
        <div class="mb-2">
          <%= label f, :node, "Jar Name", class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1">
            <%= text_input f, :node, phx_debounce: "blur", placeholder: "Jar Name", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-gray-500 focus:border-gray-500 sm:text-sm" %>
            <%= error_tag f, :node %>
          </div>
        </div>
        <div class="mb-2">
          <%= label f, :api_key, class: "block text-sm font-medium text-gray-700" %>
          <div class="mt-1">
            <%= text_input f, :api_key, phx_debounce: "blur", class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-gray-500 focus:border-gray-500 sm:text-sm" %>
            <p class="text-xs text-red-600 font-bold m-2">Copy the API Key, this won't be visiable again</p>
            <%= error_tag f, :api_key_hash %>
          </div>
        </div>
      </div>
    </div>

  </div>
  <div class="mt-5 sm:mt-4 sm:flex sm:flex-row-reverse">
    <%= submit "Save Jar", phx_disable_with: "Saving...", class: "w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-gray-600 text-base font-medium text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500 sm:ml-3 sm:w-auto sm:text-sm" %>

    <%= live_patch to: @return_to, class: "mt-3 w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:w-auto sm:text-sm" do %>
      Cancel
    <% end %>
  </div>
  </form>
</div>


  

lib/leyden_jar_web/live/jar_live/show.html.leex
<div class="container mx-auto px-4 pt-24">

<h1 class="font-bold text-2xl pb-10">Showing <%= @jar.node %> Jar</h1>

<%= if @live_action in [:edit] do %>
  <%= live_modal @socket, LeydenJarWeb.JarLive.FormComponent,
    id: @jar.id,
    title: @page_title,
    action: @live_action,
    jar: @jar,
    return_to: Routes.jar_show_path(@socket, :show, @jar) %>
<% end %>


<!-- This example requires Tailwind CSS v2.0+ -->
<div id="posts" class="flex flex-col" phx-hook="Chart">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="bg-white shadow overflow-hidden border-b border-gray-200 sm:rounded-lg p-8">
        <div>
          <label for="location" class="block text-sm font-medium text-gray-700">Session</label>
          <select id="location" name="location" class="mt-1 block w-full pl-3 pr-10 py-2 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
            <%= for session <- @jar.jar_sessions do %>
            <option value="<%= session.id %>"><%= scaleString(session.wh, 1000, 2) %> kWh</option>
            <% end %>
          </select>
        </div>

        <canvas id="myChart" height="80"></canvas>

        <div id="<%= @session.wh %>">
          <table class="px-24 min-w-full divide-y divide-gray-200">
            <thead class="">
              <tr>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  ID
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  State
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Amp
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Temp
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Free Ram
                </th>
                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Date
                </th>
                <th scope="col" class="relative px-6 py-3">
                  <%# <span class="sr-only">Edit</span> %>
                </th>
              </tr>
            </thead>
            <tbody>
              <%= for p <- @session.posts do %>
              <tr class="bg-white">

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= p.id %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= jar_state(p.body["state"]) %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= scaleString(p.body["amp"], 1000, 2) %> A
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= scaleString(p.body["temp"], 10, 1) %>&deg; C
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= scaleString(p.body["freeram"], 1024, 0) %> K
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                  <%= p.inserted_at %>
                </td>

                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                  <%# <a href="#" class="text-indigo-600 hover:text-indigo-900">Edit</a> %>
                </td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>


<span><%= live_patch "Edit", to: Routes.jar_show_path(@socket, :edit, @jar), class: "button" %></span>
<span><%= live_redirect "Back", to: Routes.jar_index_path(@socket, :index) %></span>
</div>